### ISSUE TITLE
AI army and stats don't show on local vagrant box

### ISSUE THREAD

**Issue by nickelsen** [dsjoerg/esdb#6]
1v1 replays against AIs don't show AI in the army chart or stats after uploading to the vagrant box. When I upload non-AI replays, both players show.

During the upload of the AI replay, I get the following error on `esdb` and I'm not sure how to interpret it in order to start debugging:
```
12:20:37 log.1        | E, [2016-04-17T12:20:36.544339 #21828] ERROR -- ESDB: ESDB::Identity#enqueue! was called from /vagrant/esdb/esdb/jobs/sc2/replay/post_parse.rb:50:in `block in perform'
```

No errors appear when I upload non-AI replays, so I think the missing AI is related to the error.

Any pointers where to start digging?

**Comment by dsjoerg** [comment]
Each distinct player in the battle.net system has a row in the esdb_identities database table.
It might be necessary to manually create the AI "players" so that vs-AI matches can be parsed and processed correctly.

Here's all the esdb_identities where bnet_id == 0:
https://gist.github.com/dsjoerg/74f207df77671a3df66ebb57835ddb9b

Before you add those to your database you might need to `delete from esdb_identities where bnet_id = 0`.

If adding those to your database doesn't fix it, then please run `select * from esdb_identities where bnet_id = 0` and send me the output.

What's happening here:
https://github.com/dsjoerg/esdb/blob/master/esdb/models/identity.rb#L127
is the line that's complaining.

Our (overcomplex) class hierarchy permits for each row on esdb_identities to specify what class it is.  See the `type` column in esdb_identities.  For some reason the AI identity is probably not `ESDB::Sc2::Identity` in your database as it should be.

**Comment by nickelsen** [comment]
Thanks! Adding those identies worked - I'll figure out to put those in a migration so they are in place after a vanilla install of the vagrant box.

**Comment by nickelsen** [comment]
Hmm, I guess adding them in a migration is actually not a good idea, since it will then also be done in production. I'll add them in a file similar to `replays_sq_skill_stat.sql` which I'll add to the vagrant box install script.
